---
- name: Check the encrypt file exists.
  stat: path=/etc/letsencrypt/live/{{ item.key }}
  register: result
  with_dict: "{{ letsencrypt_domains }}"

# - set_fact: cert_exists="{{ result.stat.exists }}"

- name: Ensure "{{ http_service }}" is stopped at runnning certbot.
  service: name="{{ http_service }}" state=stopped
  when: http_service != ""

- name: Run certbot certonly.
  command: certbot certonly --standalone -n --agree-tos --domain {{ item.key }} --email {{ item.value.email }}
  args:
    creates: /etc/letsencrypt/live/{{ item.key }}
  with_dict: "{{ letsencrypt_domains }}"

- name: Ensure "{{ http_service }}" is started at finished certbot.
  service: name="{{ http_service }}" state=started
  when: http_service != ""
