---
- name: Ensure "{{ http_service }}" is stopped at runnning certbot.
  service: name="{{ http_service }}" state=stopped
  when: http_service != ""

- name: Check encrypt file exists.
  stat:
    path: /etc/letsencrypt/live/{{ letsencrypt_domain }}
  register: f

- name: Run certbot certonly.
  command: certbot certonly --standalone -n --agree-tos --domain {{ letsencrypt_domain }} --email {{ letsencrypt_contact }}
  when: not f.stat.exists

- name: Ensure "{{ http_service }}" is started at finished certbot.
  service: name="{{ http_service }}" state=started
  when: http_service != ""
