---
- name: Copy renew-timer configuration in place.
  copy:
    src: letsencrypt-renew.timer
    dest: /etc/systemd/system/letsencrypt-renew.timer
  notify:
    - reload daemon
    - restart renew-timer

- name: Copy renew-service configuration in place.
  copy:
    src: letsencrypt-renew.service
    dest: /etc/systemd/system/letsencrypt-renew.service
  notify:
    - reload daemon
    - restart renew
