---
# install
- name: Ensure certbot is installed.
  yum:
    name: certbot
    enablerepo: epel

- name: Ensure lsof is installed.
  yum:
    name: lsof

# run the certonly command.
- include: certonly.yml
  when: ansible_connection != 'docker'

# configure
- include: configure.yml
  when: ansible_connection != 'docker'

# web server config
- include: nginx.yml
  when: ansible_connection != 'docker'

# service
- name: Ensure renew-timer is started and enabled to start at boot.
  service: name=letsencrypt-renew.timer state=started enabled=yes
  when: ansible_connection != 'docker'

- name: Ensure renew is started and enabled to start at boot.
  service: name=letsencrypt-renew state=started enabled=yes
  when: ansible_connection != 'docker'

# finalize
- name: Purge yum cache.
  command: yum clean all
  when: ansible_connection == 'docker'
